import fs from "fs"
import path from "path"
import Link from "next/link"

function HomePage(props) {
  console.log(props)
  return (
    <ul>
      {props.products.map((product) => (
        <li key={product.id}>
          <Link href={`/products/${product.id}`}>{product.title}</Link>
        </li>
      ))}
    </ul>
  )
}

export async function getStaticProps() {
  const rootDirectory = process.cwd()

  const filePath = path.join(rootDirectory, "data", "dummy-backend.json")

  const jsonData = await fs.readFileSync(filePath)
  const data = JSON.parse(jsonData)

  console.log("Regenerating")
  // console.log(t)

  if (!data) {
    // Suppose API fails
    return {
      redirect: {
        destination: "/no-data",
      },
    }
  }

  if (data.products.length === 0) {
    // Suppose doesn't return no data in general
    return { notFound: true }
  }

  return {
    props: {
      products: data.products,
    },
    // Incremental static generation. Number in sec, set the interval which a page will be regenerated by server side
    revalidate: 10,
  }
}

export default HomePage
